export default {
    ADD_ITEM_TO_CART: 'ADD_TO_CART',
    EDIT_ITEM_IN_CART: 'EDIT_ITEM_IN_CART',
    REMOVE_ITEM_FROM_CART: 'REMOVE_ITEM_FROM_CART',
    SAVE_CART: 'SAVE_CART',
    CLEAR_CART: 'CLEAR_CART',
    CHECKOUT: 'CHECKOUT',
};