export default {
    ADD_INTEREST: 'ADD_INTEREST',
    FETCH_INTERESTS: 'FETCH_INTERESTS',
    REMOVE_INTEREST: 'REMOVE_INTEREST',
    ADD_USER_INTEREST: 'ADD_USER_INTEREST',
    FETCH_USER_INTERESTS: 'FETCH_USER_INTERESTS',
    REMOVE_USER_INTEREST: 'REMOVE_USER_INTEREST',
    ADD_PRODUCT_INTEREST: 'ADD_PRODUCT_INTEREST',
    FETCH_PRODUCT_INTERESTS: 'FETCH_PRODUCT_INTERESTS',
    REMOVE_PRODUCT_INTEREST: 'REMOVE_PRODUCT_INTEREST',
};