export default {
    INVITE: 'INVITE',
    REQUEST_FRIEND: 'REQUEST_FRIEND',
    FETCH_FRIEND_REQUESTS: 'FETCH_FRIEND_REQUESTS',
    ACCEPT_FRIEND: 'ACCEPT_FRIEND',
    REJECT_FRIEND: 'REJECT_FRIEND',
    REMOVE_FRIEND: 'REMOVE_FRIEND',
    EDIT_FRIEND: 'EDIT_FRIEND',
    FETCH_FRIENDS: 'FETCH_FRIENDS',
};