
export const ACTIONS = {
    ADD_ERROR: 'ADD_ERROR',
    CLEAR_ERROR: 'CLEAR_ERROR',
    CANCEL_FETCHING: 'CANCEL_FETCHING',
    FETCH_REMINDERS: 'FETCH_REMINDERS',
};

export const FILTERS = {
    ACTIVE: 'ACTIVE',
    INACTIVE: 'INACTIVE',
    ACCEPTED: 'ACCEPTED',
    REJECTED: 'REJECTED',
    PENDING: 'PENDING'
};