export default {
    ADD_USER_OAUTH: 'ADD_USER_OAUTH',
    REMOVE_USER_OAUTH: 'REMOVE_USER_OAUTH',
    EDIT_USER_PREFERENCES: 'EDIT_USER_PREFERENCES',
    SAVE_USER_PREFERENCES: 'SAVE_USER_PREFERENCES',
};